services:
  postgres:
    image: postgres:16
    container_name: twenty-local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: twenty
      POSTGRES_PASSWORD: twenty
      POSTGRES_DB: twenty
    volumes:
      - twenty-local-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twenty"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: twenty-local-redis
    ports:
      - "6379:6379"
    volumes:
      - twenty-local-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  twenty-local-postgres-data:
  twenty-local-redis-data: 